security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory:
            memory: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # api:
        #     pattern:    ^/api
        #     stateless:  true
        #     anonymous:  false

        main:
            anonymous: true

    access_control:
        - { path: ^/testapi, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }     